package io.github.auspis.fluentrepo4j.repository;

import io.github.auspis.fluentrepo4j.FluentPersistable;
import io.github.auspis.fluentrepo4j.connection.FluentConnectionProvider;
import io.github.auspis.fluentrepo4j.mapping.FluentEntityInformation;
import io.github.auspis.fluentsql4j.dsl.DSL;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.PagingAndSortingRepository;

/**
 * Default implementation of {@link CrudRepository} and {@link PagingAndSortingRepository}
 * using fluent-sql-4j for SQL generation and Spring's
 * {@link org.springframework.jdbc.datasource.DataSourceUtils} for connection management.
 *
 * <p>Delegates low-level JDBC operations to {@link CoreRepositoryOperations}.
 *
 * @param <T>  the entity type
 * @param <ID> the entity identifier type
 */
public class FluentRepository<T, ID> implements CrudRepository<T, ID>, PagingAndSortingRepository<T, ID> {

    private final CoreRepositoryOperations<T, ID> core;

    public FluentRepository(
            FluentEntityInformation<T, ID> entityInformation, FluentConnectionProvider connectionProvider, DSL dsl) {
        this.core = new CoreRepositoryOperations<>(entityInformation, connectionProvider, dsl);
    }

    // ---- Save ----

    /**
     * Saves the given entity, performing an INSERT or UPDATE depending on the
     * {@link SaveAction} determined by the {@link SaveDecisionResolver}.
     *
     * @see SaveDecisionResolver for the full decision logic
     */
    @Override
    public <S extends T> S save(S entity) {
        S saved =
                switch (core.getSaveDecisionResolver().apply(entity)) {
                    case INSERT_PROVIDED_ID -> core.insertWithProvidedId(entity);
                    case INSERT_AUTO_ID -> core.insertWithIdentity(entity);
                    case UPDATE -> core.update(entity);
                    case ERROR ->
                        throw new IllegalStateException(
                                "Entity " + entity.getClass().getSimpleName()
                                        + " uses IDENTITY strategy but has a non-null ID that does not exist in the database."
                                        + " This is an inconsistent state: IDENTITY IDs are generated by the database"
                                        + " and should not be set manually for new entities.");
                };
        if (saved instanceof FluentPersistable<?> fp) {
            fp.markPersisted();
        }
        return saved;
    }

    @Override
    public <S extends T> Iterable<S> saveAll(Iterable<S> entities) {
        List<S> result = new ArrayList<>();
        for (S entity : entities) {
            result.add(save(entity));
        }
        return result;
    }

    // ---- Find ----

    @Override
    public Optional<T> findById(ID id) {
        return core.findByIdRaw(id);
    }

    @Override
    public boolean existsById(ID id) {
        return core.existsByIdRaw(id);
    }

    @Override
    public Iterable<T> findAll() {
        return core.findAllRaw(Sort.unsorted(), null);
    }

    @Override
    public Iterable<T> findAll(Sort sort) {
        return core.findAllRaw(sort, null);
    }

    @Override
    public Page<T> findAll(Pageable pageable) {
        long totalElements = count();
        if (totalElements == 0 || pageable.getOffset() >= totalElements) {
            return new PageImpl<>(List.of(), pageable, totalElements);
        }
        List<T> content = core.findAllRaw(pageable.getSort(), pageable);
        return new PageImpl<>(content, pageable, totalElements);
    }

    @Override
    public Iterable<T> findAllById(Iterable<ID> ids) {
        List<T> results = new ArrayList<>();
        for (ID id : ids) {
            findById(id).ifPresent(results::add);
        }
        return results;
    }

    @Override
    public long count() {
        return core.countRaw();
    }

    // ---- Delete ----

    @Override
    public void deleteById(ID id) {
        core.deleteByIdRaw(id);
    }

    @Override
    public void delete(T entity) {
        ID id = core.getEntityId(entity);
        if (id == null) {
            throw new IllegalArgumentException("Cannot delete entity with null ID");
        }
        deleteById(id);
    }

    @Override
    public void deleteAllById(Iterable<? extends ID> ids) {
        for (ID id : ids) {
            deleteById(id);
        }
    }

    @Override
    public void deleteAll(Iterable<? extends T> entities) {
        for (T entity : entities) {
            delete(entity);
        }
    }

    @Override
    public void deleteAll() {
        core.deleteAllRaw();
    }
}
