package io.github.auspis.fluentrepo4j.repository;

import io.github.auspis.fluentrepo4j.FluentPersistable;
import io.github.auspis.fluentrepo4j.functional.FunctionalCrudRepository;
import io.github.auspis.fluentrepo4j.functional.FunctionalPagingAndSortingRepository;
import io.github.auspis.fluentrepo4j.functional.RepositoryResult;
import io.github.auspis.fluentrepo4j.functional.RepositoryResult.Failure;
import io.github.auspis.fluentrepo4j.functional.RepositoryResult.Success;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import org.springframework.dao.OptimisticLockingFailureException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

/**
 * Functional counterpart of {@link FluentRepository}.
 *
 * <p>Implements {@link FunctionalCrudRepository} and {@link FunctionalPagingAndSortingRepository}
 * by delegating low-level JDBC operations to {@link CoreRepositoryOperations} and wrapping
 * every result in {@link RepositoryResult}. Domain-level errors such as optimistic locking
 * failures are captured as {@link Failure}; infrastructure errors propagate as Spring's
 * {@link org.springframework.dao.DataAccessException}.
 *
 * @param <T>  the entity type
 * @param <ID> the entity identifier type
 */
public class FunctionalFluentRepository<T, ID>
        implements FunctionalCrudRepository<T, ID>, FunctionalPagingAndSortingRepository<T, ID> {

    private final CoreRepositoryOperations<T, ID> core;

    public FunctionalFluentRepository(CoreRepositoryOperations<T, ID> core) {
        this.core = core;
    }

    // ---- Save ----

    @Override
    public <S extends T> RepositoryResult<S> save(S entity) {
        try {
            SaveAction action = core.getSaveDecisionResolver().apply(entity);
            S saved =
                    switch (action) {
                        case INSERT_PROVIDED_ID -> core.insertWithProvidedId(entity);
                        case INSERT_AUTO_ID -> core.insertWithIdentity(entity);
                        case UPDATE -> core.update(entity);
                        case ERROR -> null;
                    };
            if (saved == null) {
                return new Failure<>(
                        "Entity " + entity.getClass().getSimpleName()
                                + " uses IDENTITY strategy but has a non-null ID that does not exist in the database."
                                + " IDENTITY IDs are generated by the database and should not be set manually for new entities.");
            }
            if (saved instanceof FluentPersistable<?> fp) {
                fp.markPersisted();
            }
            return new Success<>(saved);
        } catch (OptimisticLockingFailureException e) {
            return new Failure<>(e.getMessage(), e);
        }
    }

    @Override
    public <S extends T> RepositoryResult<List<S>> saveAll(Iterable<S> entities) {
        List<S> results = new ArrayList<>();
        for (S entity : entities) {
            RepositoryResult<S> result = save(entity);
            if (result instanceof Failure<S>(String message, Throwable cause)) {
                return new Failure<>(message, cause);
            }
            results.add(result.orElseThrow());
        }
        return new Success<>(results);
    }

    // ---- Find ----

    @Override
    public RepositoryResult<Optional<T>> findById(ID id) {
        return new Success<>(core.findByIdRaw(id));
    }

    @Override
    public RepositoryResult<Boolean> existsById(ID id) {
        return new Success<>(core.existsByIdRaw(id));
    }

    @Override
    public RepositoryResult<List<T>> findAll() {
        return new Success<>(core.findAllRaw(Sort.unsorted(), null));
    }

    @Override
    public RepositoryResult<List<T>> findAll(Sort sort) {
        return new Success<>(core.findAllRaw(sort, null));
    }

    @Override
    public RepositoryResult<Page<T>> findAll(Pageable pageable) {
        long totalElements = core.countRaw();
        if (totalElements == 0 || pageable.getOffset() >= totalElements) {
            return new Success<>(new PageImpl<>(List.of(), pageable, totalElements));
        }
        List<T> content = core.findAllRaw(pageable.getSort(), pageable);
        return new Success<>(new PageImpl<>(content, pageable, totalElements));
    }

    @Override
    public RepositoryResult<List<T>> findAllById(Iterable<ID> ids) {
        List<T> results = new ArrayList<>();
        for (ID id : ids) {
            core.findByIdRaw(id).ifPresent(results::add);
        }
        return new Success<>(results);
    }

    @Override
    public RepositoryResult<Long> count() {
        return new Success<>(core.countRaw());
    }

    // ---- Delete ----

    @Override
    public RepositoryResult<Boolean> deleteById(ID id) {
        int affected = core.deleteByIdRaw(id);
        return new Success<>(affected > 0);
    }

    @Override
    public RepositoryResult<Boolean> delete(T entity) {
        ID id = core.getEntityId(entity);
        if (id == null) {
            return new Failure<>("Cannot delete entity with null ID");
        }
        return deleteById(id);
    }

    @Override
    public RepositoryResult<Long> deleteAllById(Iterable<? extends ID> ids) {
        long count = 0;
        for (ID id : ids) {
            if (core.deleteByIdRaw(id) > 0) {
                count++;
            }
        }
        return new Success<>(count);
    }

    @Override
    public RepositoryResult<Long> deleteAll(Iterable<? extends T> entities) {
        long count = 0;
        for (T entity : entities) {
            RepositoryResult<Boolean> result = delete(entity);
            if (Boolean.TRUE.equals(result.orElseThrow())) {
                count++;
            }
        }
        return new Success<>(count);
    }

    @Override
    public RepositoryResult<Long> deleteAll() {
        long affected = core.deleteAllRaw();
        return new Success<>(affected);
    }
}
