package io.github.auspis.fluentrepo4j.repository;

import io.github.auspis.fluentrepo4j.FluentPersistable;
import io.github.auspis.fluentrepo4j.functional.write.FunctionalWriteRepository;
import io.github.auspis.fluentrepo4j.functional.write.WriteResult;
import io.github.auspis.fluentrepo4j.functional.write.WriteResult.Error;
import io.github.auspis.fluentrepo4j.functional.write.WriteResult.Success;

import java.util.ArrayList;
import java.util.List;
import org.springframework.dao.OptimisticLockingFailureException;

public class FunctionalWriteFluentRepository<T, ID> implements FunctionalWriteRepository<T, ID> {

    private final CoreRepositoryOperations<T, ID> core;

    public FunctionalWriteFluentRepository(CoreRepositoryOperations<T, ID> core) {
        this.core = core;
    }

    @Override
    public <S extends T> WriteResult<S> save(S entity) {
        try {
            SaveAction action = core.getSaveDecisionResolver().apply(entity);
            S saved =
                    switch (action) {
                        case INSERT_PROVIDED_ID -> core.insertWithProvidedId(entity);
                        case INSERT_AUTO_ID -> core.insertWithIdentity(entity);
                        case UPDATE -> core.update(entity);
                        case ERROR -> null;
                    };
            if (saved == null) {
                return new Error<>(
                        "Entity " + entity.getClass().getSimpleName()
                                + " uses IDENTITY strategy but has a non-null ID that does not exist in the database."
                                + " IDENTITY IDs are generated by the database and should not be set manually for new entities.");
            }
            if (saved instanceof FluentPersistable<?> fp) {
                fp.markPersisted();
            }
            return new Success<>(saved);
        } catch (OptimisticLockingFailureException e) {
            return new Error<>(e.getMessage(), e);
        }
    }

    @Override
    public <S extends T> WriteResult<List<S>> saveAll(Iterable<S> entities) {
        List<S> results = new ArrayList<>();
        for (S entity : entities) {
            WriteResult<S> result = save(entity);
            if (result instanceof Error<S>(String message, Throwable cause)) {
                return new Error<>(message, cause);
            }
            results.add(result.orElseThrow());
        }
        return new Success<>(results);
    }

    @Override
    public WriteResult<Boolean> deleteById(ID id) {
        int affected = core.deleteByIdRaw(id);
        return new Success<>(affected > 0);
    }

    @Override
    public WriteResult<Boolean> delete(T entity) {
        ID id = core.getEntityId(entity);
        if (id == null) {
            return new Error<>("Cannot delete entity with null ID");
        }
        return deleteById(id);
    }

    @Override
    public WriteResult<Long> deleteAllById(Iterable<? extends ID> ids) {
        long count = 0;
        for (ID id : ids) {
            if (core.deleteByIdRaw(id) > 0) {
                count++;
            }
        }
        return new Success<>(count);
    }

    @Override
    public WriteResult<Long> deleteAll(Iterable<? extends T> entities) {
        long count = 0;
        for (T entity : entities) {
            WriteResult<Boolean> result = delete(entity);
            if (Boolean.TRUE.equals(result.orElseThrow())) {
                count++;
            }
        }
        return new Success<>(count);
    }

    @Override
    public WriteResult<Long> deleteAll() {
        long affected = core.deleteAllRaw();
        return new Success<>(affected);
    }
}
